# WSRA/agents/burp_exporter.py

import uuid
import xml.etree.ElementTree as ET
from typing import Optional, Set, Tuple
from urllib.parse import urlparse

from database.connection import SessionLocal
from database.models import AuditLog, VulnerabilityHint


class BurpExporterAgent:
    """
    Burp Suite XML Exporter (FINDINGS ONLY)

    ✔ Exports only real vulnerabilities
    ✔ Deduplicates issues
    ✔ Burp-compatible XML
    ✔ Safe: never crashes scans
    """

    # Only these actions are real security findings
    FINDING_ACTIONS = {
        "missing_csrf",
        # future:
        # "xss",
        # "sql_injection",
        # "open_redirect",
    }

    SEVERITY_MAP = {
        "missing_csrf": "Medium",
    }

    CONFIDENCE_MAP = {
        "missing_csrf": "Firm",
    }

    def export_scan(self, scan_id: str):
        db = SessionLocal()
        try:
            logs = (
                db.query(AuditLog)
                .filter(
                    AuditLog.scan_id == uuid.UUID(scan_id),
                    AuditLog.action.in_(self.FINDING_ACTIONS),
                )
                .all()
            )
            
            hints = (
                db.query(VulnerabilityHint)
                .filter(VulnerabilityHint.scan_id == uuid.UUID(scan_id))
                .all()
            )

            root = ET.Element("issues")

            # Deduplication set
            seen: Set[Tuple[str, str]] = set()

            # 1. Export AuditLog Findings (Legacy)
            for log in logs:
                details = log.details or {}
                url = details.get("url")
                if not url:
                    continue

                parsed = urlparse(url)
                host = parsed.hostname or "unknown"
                path = parsed.path or "/"

                dedup_key = (log.action, url)
                if dedup_key in seen:
                    continue
                seen.add(dedup_key)

                issue = ET.SubElement(root, "issue")

                ET.SubElement(issue, "name").text = self._format_name(log.action)
                ET.SubElement(issue, "severity").text = self.SEVERITY_MAP.get(
                    log.action, "Medium"
                )
                ET.SubElement(issue, "confidence").text = self.CONFIDENCE_MAP.get(
                    log.action, "Tentative"
                )

                ET.SubElement(issue, "host").text = host
                ET.SubElement(issue, "path").text = path

                ET.SubElement(issue, "detail").text = self._build_detail(
                    log.action, url, details
                )

                ET.SubElement(issue, "background").text = self._build_background(
                    log.action
                )
            
            # 2. Export Vulnerability Hints (New)
            for hint in hints:
                url = hint.endpoint or ""
                parsed = urlparse(url)
                host = parsed.hostname or "unknown"
                path = parsed.path or "/"

                # Dedup key: Type + Parameter + URL
                dedup_key = (f"hint_{hint.type}_{hint.parameter}", url)
                if dedup_key in seen:
                    continue
                seen.add(dedup_key)

                issue = ET.SubElement(root, "issue")
                
                # Name: "Reflected XSS Hint (q)"
                name = f"{hint.type} Hint"
                if hint.parameter:
                    name += f" ({hint.parameter})"
                ET.SubElement(issue, "name").text = name
                
                # Severity (Hints are usually High if they trigger)
                ET.SubElement(issue, "severity").text = "High" if hint.confidence >= 0.8 else "Medium"
                
                # Confidence Map
                conf_text = "Tentative"
                if hint.confidence >= 0.9: conf_text = "Certain"
                elif hint.confidence >= 0.7: conf_text = "Firm"
                ET.SubElement(issue, "confidence").text = conf_text

                ET.SubElement(issue, "host").text = host
                ET.SubElement(issue, "path").text = path
                ET.SubElement(issue, "location").text = hint.parameter or ""
                
                # Detail: Evidence + Manual Test
                detail_text = f"<b>Parameter:</b> {hint.parameter}<br/>"
                detail_text += f"<b>Evidence:</b> {hint.evidence}<br/><br/>"
                detail_text += f"<b>Manual Test:</b><br/>{hint.manual_test}"
                ET.SubElement(issue, "detail").text = detail_text

                ET.SubElement(issue, "background").text = (
                    "This is a hypothesis generated by the Vulnerability Hinter agent. "
                    "It has not been actively exploited, but patterns suggest a high likelihood of vulnerability."
                )

            # Now save to DB as 'xml'
            xml_content = ET.tostring(root, encoding='utf-8', xml_declaration=True).decode('utf-8')
            from database.models import Export
            existing = db.query(Export).filter_by(scan_id=uuid.UUID(scan_id), format="xml").first()
            if existing:
                existing.content = xml_content
            else:
                db.add(Export(scan_id=uuid.UUID(scan_id), format="xml", content=xml_content))
            db.commit()

            print(f"[BURP] Exported {len(seen)} unique findings to database")
            return True


        except Exception as exc:
            print(f"[BURP] Export failed: {exc}")

        finally:
            db.close()

    # -----------------------
    # Helper methods
    # -----------------------

    def _format_name(self, action: str) -> str:
        if action == "missing_csrf":
            return "Missing CSRF Protection"
        return action.replace("_", " ").title()

    def _build_detail(self, action: str, url: str, details: dict) -> str:
        if action == "missing_csrf":
            return (
                f"A form or state-changing endpoint at {url} "
                f"was detected without a CSRF protection mechanism. "
                f"This may allow attackers to perform unauthorized actions "
                f"on behalf of an authenticated user."
            )
        return f"Issue detected at {url}."

    def _build_background(self, action: str) -> str:
        if action == "missing_csrf":
            return (
                "Cross-Site Request Forgery (CSRF) vulnerabilities occur when "
                "an application does not properly validate whether a request "
                "originated from a trusted user. This can allow attackers to "
                "trick authenticated users into performing unintended actions."
            )
        return "Issue generated by WSRA scanner."
